baseurl = "localhost:1313"
languageCode = "en-us"
theme = "hugo-elate-theme"
title = "Kidds Ice Creams"
[params]
author = ""
custom_css = ["css/custom1.css", "css/custom2.css"]
description = ""
email = "prashanthdevkumar@gmail.com"
[params.about]
description = "Kidds Ice Creams (KIC) is an ice cream manufacturing unit located at Mysuru, India. The company was founded in 1999. Today, the company possesses its own infrastructure that includes land, building, machinery and logistics management.KIC consists of eight core employees and variable number of contract workers depending on the seasonal business environment and demand. The production facility is capable of producing two tones of ice cream per day. The organization caters its products through many distribution channels that include retail outlets, party orders and direct sales. Party orders include ice cream supplies to marriage functions and social gatherings. Direct sales involve selling the products through mobile vans (three wheeler vehicles) in the rural outskirts and public gatherings such as exhibitions and regional festivities.<br/><br/> Kidds Ice Creams has held an immaculate track record of providing superlative quality in the form of both its products and services to its esteemed customers. The products are FSSCAI (Food Safety Standard and Authority of India) certified, manufactured in pristine production environment."
enable = true
title = "About"
[[params.about.item]]
alt = "Devakumar"
description = "I graduated from the National Dairy Research Institute (NDRI) in Dairy Technology in 1979.<br/><br/>Started my career at Aavin (Tamil Nadu Co-operative Milk Producersâ€™ Federation Limited) Ooty, Tamil Nadu and served as Assistant Manager (Dairy & Cheese) in different capacities during my tenure for 11 years and later served as Production Manager at a private ice cream manufacturing plant for 9 years before starting Kidds Ice Creams in 1999.<br/><br/>I have been in the dairy and ice cream industry for 37 years now and hold  proficiency and knowledge about the business springing from my professional experience."
img = "hero_dad.JPG"
name = "Devakumar Ananthanarayana"
position = "Founder & CEO"
social = [["icon-twitter", "#"], ["icon-facebook", "#"], ["icon-linkedin", "#"]]
[params.contact]
button = "Send message"
description = "What can we do for you? From cups, cones to party orders."
details = [["icon-home", "256 Hebbal Industrial Area, <br> Mysuru, Karnataka 570018"], ["icon-phone", "+91 821-2403232"], ["icon-envelope", "kiddsicecreams@gmail.com"], ["icon-globe", "<a href=\"http://kiddsicecreams.com\" target=\"_blank\">kiddsicecreams.com</a>"]]
email = "Email"
enable = true
map = true
message = "Message"
name = "Name"
phone = "Phone"
title = "Get in touch"
[params.footer]
copyright = "&copy; Kidds Ice Creams. All Rights Reserved."
enable = true

[params.hero]
subtitle = "Once is not Enough"
title = "Kidds Ice Creams."

# [params.intro]
#
# [[params.intro.item]]
#   title = "Plan"
#   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
#   url = "#"
#   button = "Get In Touch"
#   icon = "icon-bulb"
#   img = "img_7.jpg"


[params.navigation]
about = "About"
brand = "Kidds Ice Creams"
contact = "Contact"
home = "Home"
work = "Gallery"

[params.work]
  enable = true
  title = "Gallery"
  description = ""
  footertext = ""

  [[params.work.row]]
    img = "g6.jpg"
    alt = "Image2"
    title = ""
    subtitle = ""

  [[params.work.row]]
    img = "g2.jpg"
    alt = "Image2"
    title = ""
    subtitle = ""

  [[params.work.row]]
    img = "g3.jpg"
    alt = "Image3"
    title = ""
    subtitle = ""

  [[params.work.row]]
    img = "g4.jpg"
    alt = "Image4"
    title = ""
    subtitle = ""

  [[params.work.row]]
    img = "g5.jpg"
    alt = "Image5"
    title = ""
    subtitle = ""

  [[params.work.row]]
    img = "g1.jpg"
    alt = "Image6"
    title = ""
    subtitle = ""
